/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* always defined to indicate that i18n is enabled */
#define ENABLE_NLS 1

/* foo */
#define GETTEXT_PACKAGE "totem"

/* Define to 1 if you have the `bind_textdomain_codeset' function. */
#define HAVE_BIND_TEXTDOMAIN_CODESET 1

/* Define to 1 if you have the `dcgettext' function. */
#define HAVE_DCGETTEXT 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define if the GNU gettext() function is already present or preinstalled. */
#define HAVE_GETTEXT 1

/* Whether we use Gst 0.8 or 0.10 */
/* #undef HAVE_GSTREAMER_010 */

/* defined if GNOME isn't used */
/* #undef HAVE_GTK_ONLY */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if your <locale.h> file defines LC_MESSAGES. */
#define HAVE_LC_MESSAGES 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define if you build the mozilla plugin */
#define HAVE_MOZILLA 1

/* defined if you build the nautilus plugin */
#define HAVE_NAUTILUS 1

/* Define to 1 if nvtv is available and used. */
/* #undef HAVE_NVTV */

/* defined if you have lirc library */
/* #undef HAVE_REMOTE */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* defined on x86 machines */
#define HAVE_X86 1

/* defined if you have X11/XF86keysym.h */
#define HAVE_XFREE 1

/* defined if you have XTest library */
#define HAVE_XTEST 1

/* Define this if you have the XVidMode and XRandR extension installed */
#define HAVE_XVIDMODE 

/* ISO codes prefix */
#define ISO_CODES_PREFIX "/usr"

/* package name */
#define PACKAGE "totem"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "http://bugzilla.gnome.org/enter_bug.cgi?product=totem"

/* Define to the full name of this package. */
#define PACKAGE_NAME "totem"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "totem 1.3.90"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "totem"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.3.90"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define if DEBUG statements should be compiled in */
/* #undef TOTEM_DEBUG */

/* defined if we don't have GNOME */
/* #undef USE_STABLE_LIBGNOMEUI */

/* package version */
#define VERSION "1.3.90"

/* Define if D-BUS is enabled */
#define WITH_DBUS 1
